name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        node: ['16']

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup the Node ${{ matrix.node }} environment on ${{ runner.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore the Yarn cache directory
        id: yarncache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarncache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.node }}-yarn-

      - name: Install dependencies using Yarn
        run: yarn install --frozen-lockfile

      - name: Build and compile assets
        run: |
          yarn build
          cat public/mix-manifest.json
